-- Find all the Toy Story movies

SELECT * FROM movies WHERE title LIKE "%Toy%";

-- Find all the movies directed by John Lasseter

SELECT * FROM movies WHERE director LIKE "John Lasseter";

-- Find all the movies (and director) not directed by John Lasseter

SELECT title, director FROM movies WHERE director NOT LIKE "John Lasseter";

-- Find all the WALL-* movies

SELECT * FROM movies WHERE title LIKE "wall-_";